In [6]:
%pip install pandas
%pip install numpy
import pandas as pd
import numpy as np

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [7]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer


In [8]:
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df= pd.read_csv(r"C:\Users\LENOVO\OneDrive\Desktop\New folder\Hate-Speech-Detection-Flask-App\data.csv")

In [10]:
df.head()

class                                           comments
0      1                              you are sick upstairs
1      0  i really dont understand your pointxa0 it seem...
2      0  axcxa0majority of canadians can and has been w...
3      0  sdl ok but i would hope theyd sign him to a on...
4      0                         yeah and where are you now

In [11]:
df.size

8744

In [12]:
df.columns

Index(['class', 'comments'], dtype='object')

In [13]:
#checking for datatypes
df.dtypes

class        int64
comments    object
dtype: object

In [14]:
#checking for missing nan
df.isnull().isnull().sum()

class       0
comments    0
dtype: int64

In [15]:
df_data = df[["class", "comments"]]

In [16]:
df_data.columns

Index(['class', 'comments'], dtype='object')

In [17]:
df_x = df_data["comments"]
df_y = df_data["class"]

In [18]:
#Feature Extraction from Text

cv = TfidfVectorizer()
ex = cv.fit_transform(["Hello baby gitl", "My Nigga wetin dey"])

In [19]:
ex.toarray()

array([[0.57735027, 0.        , 0.57735027, 0.57735027, 0.        ,
        0.        , 0.        ],
       [0.        , 0.5       , 0.        , 0.        , 0.5       ,
        0.5       , 0.5       ]])

In [21]:
cv.get_feature_names_out()

array(['baby', 'dey', 'gitl', 'hello', 'my', 'nigga', 'wetin'],
      dtype=object)

In [23]:
corpus = df_x
cv = TfidfVectorizer()
X = cv.fit_transform(corpus)

In [24]:
X.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(4372, 18923))

In [26]:
cv.get_feature_names_out()

array(['00', '000', '0000', ..., 'zuckenberg', 'zuckerberg',
       'zuckerbergxa0is'], shape=(18923,), dtype=object)

In [27]:
#model Building

from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, df_y, test_size=0.3, random_state=42)

In [29]:
X_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 71327 stored elements and shape (3060, 18923)>

In [30]:
#logistic Regression 81%

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.7865853658536586

In [31]:
# #naive bayes 77%

# from sklearn.naive_bayes import MultinomialNB
# clf = MultinomialNB()
# clf.fit(X_train, y_train)
# clf.score(X_test, y_test)

In [32]:
clf.predict(X_test)

array([1, 0, 0, ..., 0, 0, 0], shape=(1312,))

In [33]:
#sample prediction
comment = ['Hello fine boy']
vect = cv.transform(comment).toarray() 

In [34]:
clf.predict(vect)

array([0])

In [35]:
if clf.predict(vect) == 1:
    print("Hate Speech")
else:
    print("Not Hate Speech")

Not Hate Speech


In [36]:
#sample prediction 2
comment2 = ['fuck you nigga']
vect2 = cv.transform(comment2).toarray()
clf.predict(vect2)

array([1])

In [37]:
import pickle

In [38]:
logisticML = open("myFinalModel.pkl", "wb")

In [56]:
pickle.dump(clf, logisticML)

In [39]:
logisticML.close()

In [40]:


#load the model
my_model = open("myFinalModel.pkl", "rb")
new_model = pickle.load(my_model)

EOFError: Ran out of input